spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pzris
    username: student
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

